### ISSUE TITLE
New : Ability to connect multiple Matomo accounts

### ISSUE THREAD

**Issue by cmantika-dev** [matomo-org/looker-studio-connector#66]
We are an agency and we have several clients who have their own Matomo accounts and we also have our own with several clients on it. However, currently we can only connect one single Matomo account which is not practical.

Is it possible to add a feature to manage multiple accounts?

Thank you for your understanding.

**Comment by diosmosis** [comment]
Hi @cmantika-dev, thanks for taking the time to create an issue! This is a known issue and we currently have another issue for this feature here: https://github.com/matomo-org/looker-studio-connector/issues/2. We may be able to look into this in the future, though not immediately.

Since an issue already exists, I'll close this, but we are definitely aware it is something many users want.
